version: '3.4'

services:
  support-ticket-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: support_ticket_db
    volumes:
      - ./.containers/database:/var/opt/mssql/data
    ports:
      - "1434:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Strong_password_123!"